# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpticalDownloader
                                 A QGIS plugin
 This plugin is used to download satellite images from optical remote sensing sensors
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-01
        copyright            : (C) 2026 by Ilias Machairas
        email                : iliasmachairas@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpticalDownloader class from file OpticalDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .optical_downloader import OpticalDownloader
    return OpticalDownloader(iface)
