# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpticalDownloader
                                 A QGIS plugin
 This plugin is used to download satellite images from optical remote sensing sensors
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ilias Machairas
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import json
from datetime import datetime, timedelta

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QUrl
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import (
    Qgis, QgsMessageLog, QgsCoordinateReferenceSystem, QgsCoordinateTransform,
    QgsGeometry, QgsProject,
)
from qgis.gui import QgsMapToolPan

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .optical_downloader_dialog import OpticalDownloaderDialog
from .extent_tool import ExtentDrawingTool
from .worker import DownloadWorker


class OpticalDownloader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface      = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n',
            'OpticalDownloader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions     = []
        self.menu        = self.tr(u'&Optical Downloader')
        self.first_start = None
        self.worker      = None
        self.dlg         = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('OpticalDownloader', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon   = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/optical_downloader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Optical Satellite Downloader'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Optical Downloader'), action)
            self.iface.removeToolBarIcon(action)

    # ── Signal handlers ───────────────────────────────────────────────────────

    def _browse_output(self):
        folder = QFileDialog.getExistingDirectory(
            self.dlg, "Select output directory",
            self.dlg.lineEdit_output.text() or os.path.expanduser("~"),
        )
        if folder:
            self.dlg.lineEdit_output.setText(folder)

    def _select_all_clouds(self):
        for cb in (self.dlg.cb_cloud_shadows, self.dlg.cb_cloud_low,
                   self.dlg.cb_cloud_med, self.dlg.cb_cloud_high, self.dlg.cb_cirrus):
            cb.setChecked(True)

    def _unselect_all_clouds(self):
        for cb in (self.dlg.cb_cloud_shadows, self.dlg.cb_cloud_low,
                   self.dlg.cb_cloud_med, self.dlg.cb_cloud_high, self.dlg.cb_cirrus):
            cb.setChecked(False)

    def _start_draw_tool(self):
        """Minimise dialog and activate the rubber-band drawing tool."""
        self.dlg.setWindowState(Qt.WindowState.WindowMinimized)
        tool = ExtentDrawingTool(self.iface.mapCanvas(), self._handle_extent)
        self.iface.mapCanvas().setMapTool(tool)
        self.dlg.set_status("Draw a rectangle on the map…")

    def _handle_extent(self, xmin, ymin, xmax, ymax):
        """Callback from ExtentDrawingTool — fills coordinate fields."""
        self.dlg.set_aoi_from_extent(xmin, ymin, xmax, ymax)
        self.dlg.setWindowState(Qt.WindowState.WindowNoState)
        self.dlg.raise_()
        self.dlg.activateWindow()
        self.dlg.set_status(
            f"AOI: {xmin:.4f}, {ymin:.4f}  →  {xmax:.4f}, {ymax:.4f}")
        self.iface.mapCanvas().setMapTool(QgsMapToolPan(self.iface.mapCanvas()))

    def _show_help(self):
        """Open the online documentation (usage guide) in the system's default browser."""
        QDesktopServices.openUrl(
            QUrl("https://optical-downloader.readthedocs.io/en/latest/usage.html"))

    # ── Download logic ────────────────────────────────────────────────────────

    def _aoi_geojson_from_layer(self, layer):
        """Build an EPSG:4326 GeoJSON Feature covering every feature in `layer`,
        reprojected and unioned into a single (multi)polygon geometry."""
        if layer.featureCount() == 0:
            raise ValueError(f"Layer '{layer.name()}' has no features.")

        wgs84     = QgsCoordinateReferenceSystem("EPSG:4326")
        transform = QgsCoordinateTransform(layer.crs(), wgs84, QgsProject.instance())

        geometries = []
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if geom is None or geom.isEmpty():
                continue
            geom = QgsGeometry(geom)
            geom.transform(transform)
            geometries.append(geom)

        if not geometries:
            raise ValueError(f"Layer '{layer.name()}' has no valid geometries.")

        union = QgsGeometry.unaryUnion(geometries)
        if union.isEmpty():
            raise ValueError(f"Could not combine the geometries in '{layer.name()}'.")

        return {
            "type": "Feature",
            "properties": {"name": layer.name()},
            "geometry": json.loads(union.asJson()),
        }

    def _run_download(self):
        d = self.dlg

        # Validate AOI
        points_list = None
        aoi_geojson = None
        aoi_bounds_msg = ""

        if d.get_aoi_source() == "draw":
            try:
                xmin, ymin, xmax, ymax = d.get_aoi_coords()
            except ValueError as e:
                self.iface.messageBar().pushMessage(
                    "Input Error", str(e), level=Qgis.MessageLevel.Critical, duration=5)
                return
            points_list = [
                [xmin, ymax],  # top-left
                [xmax, ymax],  # top-right
                [xmax, ymin],  # bottom-right
                [xmin, ymin],  # bottom-left
            ]
            aoi_bounds_msg = f"AOI (drawn) ({xmin:.4f},{ymin:.4f})→({xmax:.4f},{ymax:.4f})"
        else:
            layer = d.get_aoi_layer()
            if layer is None:
                self.iface.messageBar().pushMessage(
                    "Input Error", "Please select a polygon layer.",
                    level=Qgis.MessageLevel.Critical, duration=5)
                return
            try:
                aoi_geojson = self._aoi_geojson_from_layer(layer)
            except ValueError as e:
                self.iface.messageBar().pushMessage(
                    "Input Error", str(e), level=Qgis.MessageLevel.Critical, duration=5)
                return
            aoi_bounds_msg = f"AOI (layer) '{layer.name()}'"

        # Validate output directory
        output_dir = d.get_output_dir()
        if not output_dir:
            self.iface.messageBar().pushMessage(
                "Input Error", "Please select an output directory.",
                level=Qgis.MessageLevel.Critical, duration=5)
            return

        # Build date range string
        selected_date = d.get_selected_date()
        extra_days    = d.get_extra_days()
        dt            = datetime.strptime(selected_date, "%Y-%m-%d")
        date_str      = (
            f"{(dt - timedelta(days=extra_days)).strftime('%Y-%m-%d')}/"
            f"{(dt + timedelta(days=extra_days)).strftime('%Y-%m-%d')}"
        )

        params = {
            "points_list":         points_list,
            "aoi_geojson":         aoi_geojson,
            "date_str":            date_str,
            "platform":            d.get_platform(),
            "band_selection":      d.get_band_selection(),
            "max_cloud_tile":      d.get_max_cloud_tile(),
            "max_cloud_tolerance": d.get_max_cloud_tol(),
            "excluded_flags":      d.get_excluded_flags(),
            "output_directory":    output_dir,
            "create_report":       d.cb_report.isChecked(),
        }

        QgsMessageLog.logMessage(
            f"Download started — {params['platform']} | {date_str} | {aoi_bounds_msg}",
            "OpticalDownloader",
        )

        self.worker = DownloadWorker(params)
        self.worker.progress.connect(d.set_progress)
        self.worker.message.connect(d.set_status)
        self.worker.finished.connect(self._on_finished)
        self.worker.error.connect(self._on_error)

        d.set_running(True)
        d.set_progress(0)
        d.set_status("Starting…")
        self.worker.start()

    def _on_finished(self, result: dict):
        self.dlg.set_running(False)
        status      = result.get("status", "unknown")
        aoi_warning = result.get("aoi_warning")

        if status == "downloaded":
            out = result.get("output_path", "")
            msg = f"Done: {os.path.basename(out)}"
            self.dlg.set_status(msg)
            self.iface.messageBar().pushMessage(
                "Success", f"Saved to {out}", level=Qgis.MessageLevel.Success, duration=6)
            QgsMessageLog.logMessage(f"Output: {out}", "OpticalDownloader")
            if self.dlg.cb_open_output.isChecked() and os.path.isdir(os.path.dirname(out)):
                os.startfile(os.path.dirname(out))

        elif status == "skipped":
            msg = "Skipped — cloud cover exceeded tolerance. See report."
            self.dlg.set_status(msg)
            self.iface.messageBar().pushMessage(
                "Skipped", msg, level=Qgis.MessageLevel.Warning, duration=6)
        else:
            self.dlg.set_status(f"Finished with status: {status}")

        if aoi_warning:
            self.iface.messageBar().pushMessage(
                "Incomplete AOI coverage", aoi_warning, level=Qgis.MessageLevel.Warning, duration=15)
            QgsMessageLog.logMessage(aoi_warning, "OpticalDownloader", Qgis.MessageLevel.Warning)

    def _on_error(self, error_msg: str):
        self.dlg.set_running(False)
        self.dlg.set_progress(0)
        self.dlg.set_status("Error — see QGIS log panel for details.")
        self.iface.messageBar().pushMessage(
            "Error", error_msg.splitlines()[0], level=Qgis.MessageLevel.Critical, duration=10)
        QgsMessageLog.logMessage(error_msg, "OpticalDownloader", Qgis.MessageLevel.Critical)

    # ── Entry point ───────────────────────────────────────────────────────────

    def run(self):
        """Run method that performs all the real work."""
        if self.first_start:
            self.first_start = False
            self.dlg = OpticalDownloaderDialog()

            # Wire all interactive buttons (done once)
            self.dlg.toolButton.clicked.connect(self._browse_output)
            self.dlg.btn_select_all.clicked.connect(self._select_all_clouds)
            self.dlg.btn_unselect_all.clicked.connect(self._unselect_all_clouds)
            self.dlg.btn_draw_area.clicked.connect(self._start_draw_tool)
            self.dlg.btn_run.clicked.connect(self._run_download)
            self.dlg.btn_close.clicked.connect(self.dlg.close)
            self.dlg.btn_help.clicked.connect(self._show_help)

        if self.dlg.isVisible():
            self.dlg.raise_()
            self.dlg.activateWindow()
            return

        self.dlg.show()
