# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpticalDownloaderDialog
                                 A QGIS plugin
 This plugin is used to download satellite images from optical remote sensing sensors
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ilias Machairas
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QButtonGroup
from qgis.core import QgsProject, QgsWkbTypes, QgsMapLayerType

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'optical_downloader_dialog_base.ui'))

# Widgets shown only in "Draw on map" AOI mode
_DRAW_WIDGETS = (
    "btn_draw_area", "label_top", "lineEdit_top", "label_left", "lineEdit_left",
    "label_right", "lineEdit_right", "label_bottom", "lineEdit_bottom",
)
# Widgets shown only in "From layer" AOI mode
_LAYER_WIDGETS = ("lineEdit_layer_filter", "comboBox_aoi_layer", "label_aoi_layer_hint")


class OpticalDownloaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(OpticalDownloaderDialog, self).__init__(parent)
        self.setupUi(self)

        # Keep platform radios exclusive with each other but separate from band radios.
        # All radio buttons share the same QDialog parent, so Qt would treat all of
        # them as one exclusive group without explicit QButtonGroups.
        self.platformGroup = QButtonGroup(self)
        self.platformGroup.addButton(self.radioBtn_sentinel, 0)
        self.platformGroup.addButton(self.radioBtn_landsat, 1)

        self.bandGroup = QButtonGroup(self)
        self.bandGroup.addButton(self.radioBtn_all, 0)
        self.bandGroup.addButton(self.radioBtn_rgb, 1)
        self.bandGroup.addButton(self.radioBtn_rgb_nir_swir, 2)

        self.aoiGroup = QButtonGroup(self)
        self.aoiGroup.addButton(self.radioBtn_aoi_draw, 0)
        self.aoiGroup.addButton(self.radioBtn_aoi_layer, 1)
        self.radioBtn_aoi_draw.toggled.connect(self._update_aoi_mode)
        self._update_aoi_mode()

        self.lineEdit_layer_filter.textChanged.connect(self._populate_layer_combo)

        self.calendarWidget.selectionChanged.connect(self._update_selected_date_label)
        self._update_selected_date_label()

    # ── AOI mode ──────────────────────────────────────────────────────────────

    def _update_aoi_mode(self):
        draw_mode = self.radioBtn_aoi_draw.isChecked()
        for name in _DRAW_WIDGETS:
            getattr(self, name).setVisible(draw_mode)
        for name in _LAYER_WIDGETS:
            getattr(self, name).setVisible(not draw_mode)
        if not draw_mode:
            self._populate_layer_combo()

    def _populate_layer_combo(self):
        """Refill the layer combo with polygon vector layers matching the filter text."""
        filter_text = self.lineEdit_layer_filter.text().strip().lower()
        current_id  = self.comboBox_aoi_layer.currentData()

        self.comboBox_aoi_layer.blockSignals(True)
        self.comboBox_aoi_layer.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() != QgsMapLayerType.VectorLayer:
                continue
            if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
                continue
            if filter_text and filter_text not in layer.name().lower():
                continue
            self.comboBox_aoi_layer.addItem(layer.name(), layer.id())

        if current_id is not None:
            idx = self.comboBox_aoi_layer.findData(current_id)
            if idx >= 0:
                self.comboBox_aoi_layer.setCurrentIndex(idx)
        self.comboBox_aoi_layer.blockSignals(False)

    # ── Date label ────────────────────────────────────────────────────────────

    def _update_selected_date_label(self):
        date_str = self.calendarWidget.selectedDate().toString("yyyy-MM-dd")
        self.label_selectedDate.setText(f"Selected: {date_str}")

    # ── Typed getters ─────────────────────────────────────────────────────────

    def get_platform(self):
        return "sentinel-2-l2a" if self.radioBtn_sentinel.isChecked() else "landsat-c2-l2"

    def get_band_selection(self):
        if self.radioBtn_rgb.isChecked():
            return "rgb_only"
        if self.radioBtn_rgb_nir_swir.isChecked():
            return "rgb_nir_swir"
        return "all_bands"

    def get_excluded_flags(self):
        mapping = {
            self.cb_cloud_shadows: "Cloud shadows",
            self.cb_cloud_low:     "Clouds low probability",
            self.cb_cloud_med:     "Cloud medium probability",
            self.cb_cloud_high:    "Cloud high probability",
            self.cb_cirrus:        "Thin cirrus",
        }
        return [name for cb, name in mapping.items() if cb.isChecked()]

    def get_aoi_source(self):
        return "draw" if self.radioBtn_aoi_draw.isChecked() else "layer"

    def get_aoi_coords(self):
        """Return (xmin, ymin, xmax, ymax) as floats, raise ValueError if invalid."""
        try:
            top    = float(self.lineEdit_top.text())
            bottom = float(self.lineEdit_bottom.text())
            left   = float(self.lineEdit_left.text())
            right  = float(self.lineEdit_right.text())
        except ValueError:
            raise ValueError("AOI coordinates must be valid decimal numbers.")
        if left >= right or bottom >= top:
            raise ValueError("Invalid AOI: left < right and bottom < top required.")
        return left, bottom, right, top  # xmin, ymin, xmax, ymax

    def get_aoi_layer(self):
        """Return the QgsVectorLayer selected in the 'From layer' combo, or None."""
        layer_id = self.comboBox_aoi_layer.currentData()
        if layer_id is None:
            return None
        return QgsProject.instance().mapLayer(layer_id)

    def get_extra_days(self):
        return self.spinBox_extraDays.value()

    def get_max_cloud_tile(self):
        try:
            return int(self.lineEdit_maxCloudTile.text())
        except ValueError:
            return 100

    def get_max_cloud_tol(self):
        try:
            return int(self.lineEdit_maxCloudTol.text())
        except ValueError:
            return 20

    def get_selected_date(self):
        return self.calendarWidget.selectedDate().toString("yyyy-MM-dd")

    def get_output_dir(self):
        return self.lineEdit_output.text().strip()

    # ── UI helpers ────────────────────────────────────────────────────────────

    def set_aoi_from_extent(self, xmin, ymin, xmax, ymax):
        self.lineEdit_left.setText(f"{xmin:.6f}")
        self.lineEdit_right.setText(f"{xmax:.6f}")
        self.lineEdit_bottom.setText(f"{ymin:.6f}")
        self.lineEdit_top.setText(f"{ymax:.6f}")

    def set_status(self, message):
        self.label_status.setText(message)

    def set_progress(self, value):
        self.progressBar.setValue(value)

    def set_running(self, running: bool):
        self.btn_run.setEnabled(not running)
        self.btn_close.setEnabled(not running)
